# Site settings
name: Erwan d'Orgeville
job: "Développeur logiciel @&nbsp;SACO"
job_en: "Software developer @&nbsp;SACO"
title: "Erwan d'Orgeville - Développeur logiciel"
email: e@dor.ge
face:
    url: /img/freshwan.jpg
    alt: Erwan
description: "Typescripteur. Un peu de node-red, dans le passé beaucoup de TouchDesigner, un amour éternel pour Rails. En ce moment, je focus sur les objets connectés, Docker, mélanger les deux et plus encore!"
description_en: "Typescripter. A bit of node-red, used to do a lot of TouchDesigner, forever in love with Rails. Currently into IoT, docker, mixing both and more!"
baseurl: "" 
url: "https://dor.ge"
clean_url: "dor.ge"
og_image: "//og.erwandorgeville.com/screenshot.png"
username: &username edorgeville
github_username: *username
stackoverflow_user_id: 2105371
stackoverflow_username: *username
facebook_username: *username
facebook_user_id: 1667524238
twitter_username: *username
linkedin_username: *username
phone: "+1 514.371.7943"
phone_number: "+15143717943"
analytics_id: "UA-36343347-1"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

collections:
    - projects
gems:
  - jekyll-redirect-from
