# Site settings
name: Erwan d'Orgeville
job: "Développeur système @&nbsp;Moment&nbsp;Factory"
job_en: "System developer @&nbsp;Moment&nbsp;Factory"
title: "Erwan d'Orgeville - Développeur système"
email: info@erwandorgeville.com
face:
    url: /img/freshwan.jpg
    alt: Erwan
description: "Je fais pas mal de node-red. Des fois un peu de Rails, dans le passé beaucoup de TouchDesigner. En ce moment, je focus sur les objets connectés, Docker, mélanger les deux et plus encore!"
description_en: "I do quite a lot of node-red. Sometimes some Rails, used to do TouchDesigner. Currently into IoT, docker, mixing both and more!"
baseurl: "" 
url: "https://erwandorgeville.com"
clean_url: "erwandorgeville.com"
og_image: "//og.erwandorgeville.com/screenshot.png"
username: &username edorgeville
github_username: *username
stackoverflow_user_id: 2105371
stackoverflow_username: *username
facebook_username: *username
facebook_user_id: 1667524238
twitter_username: *username
linkedin_username: *username
phone: "+1 514.371.7943"
phone_number: "+15143717943"
analytics_id: "UA-36343347-1"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed

collections:
    - projects
