# Site settings
name: Erwan d'Orgeville
job: Développeur Web
title: Erwan d'Orgeville - Développeur Web
email: info@erwandorgeville.com
face:
    url: /img/freshwan.jpg
    alt: Erwan
description: Code et déploie des sites statiques / dynamiques / interactifs / applicatifs / innovateurs / etc. en HTML5 / CSS3 / JS / PHP / Ruby on Rails / NodeJS / la prochaine grosse affaire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erwandorgeville.com" # the base hostname & protocol for your site
og_image: "http://og.erwandorgeville.com/screenshot.png"
username: &username th3m4ri0
github_username: *username
facebook_username: *username
twitter_username: *username
linkedin_username: *username
freelancer_username: *username
phone: "+1 514.371.7943"
phone_number: "+15143717943"
analytics_id: "UA-36343347-1"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed