# Site settings
name: Erwan d'Orgeville
job: "Développeur web & interactif"
title: "Erwan d'Orgeville - Développeur web & interactif"
email: info@erwandorgeville.com
face:
    url: /img/freshwan.jpg
    alt: Erwan
description: "Développeur front-end et back-end (fan de Ruby <img src='/img/ruby.png' height=15 %>). Adepte de TouchDesigner. Actif sur Facebook, mais pas sur Twitter."
baseurl: "" 
url: "http://erwandorgeville.com"
clean_url: "erwandorgeville.com"
og_image: "http://og.erwandorgeville.com/screenshot.png"
username: &username th3m4ri0
username_clean: &username_clean edorgeville
github_username: *username_clean
stackoverflow_user_id: 2105371
stackoverflow_username: *username
facebook_username: *username_clean
facebook_user_id: 1667524238
twitter_username: *username_clean
linkedin_username: *username_clean
freelancer_username: *username
phone: "+1 514.371.7943"
phone_number: "+15143717943"
analytics_id: "UA-36343347-1"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed

collections:
    - projects
