# Site settings
name: Erwan d'Orgeville
job: "Développeur interactif & web"
job_en: "Interactive and web developer"
title: "Erwan d'Orgeville - Développeur interactif & web"
email: info@erwandorgeville.com
face:
    url: /img/freshwan.jpg
    alt: Erwan
description: "Développeur interactif (TouchDesigner) et back-end (Rails <img src='/img/ruby.png' height=15 %>). Actif sur Facebook, mais pas sur Twitter."
description_en: "Interactive (TouchDesigner) and back-end (Rails <img src='/img/ruby.png' height=15 %>) developer. Active on Facebook, not on Twitter."
baseurl: "" 
url: "https://erwandorgeville.com"
clean_url: "erwandorgeville.com"
og_image: "//og.erwandorgeville.com/screenshot.png"
username: &username th3m4ri0
username_clean: &username_clean edorgeville
github_username: *username_clean
stackoverflow_user_id: 2105371
stackoverflow_username: *username_clean
facebook_username: *username_clean
facebook_user_id: 1667524238
twitter_username: *username_clean
linkedin_username: *username_clean
freelancer_username: *username
phone: "+1 514.371.7943"
phone_number: "+15143717943"
analytics_id: "UA-36343347-1"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed

collections:
    - projects
